# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/environment.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61pi/environment.proto\x12\x0b\x65nvironment\")\n\x10GetStatesRequest\x12\x15\n\rinstance_name\x18\x01 \x01(\t\"$\n\x11GetStatesResponse\x12\x0f\n\x07metrics\x18\x01 \x03(\x02\"\x8d\x01\n\x13\x41pplyActionsRequest\x12\x15\n\rinstance_name\x18\x01 \x01(\t\x12\x38\n\x07\x61\x63tions\x18\x02 \x03(\x0b\x32\'.environment.ApplyActionsRequest.Action\x1a%\n\x06\x41\x63tion\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\"\x16\n\x14\x41pplyActionsResponse\"0\n\x17GetRewardMetricsRequest\x12\x15\n\rinstance_name\x18\x01 \x01(\t\"8\n\x18GetRewardMetricsResponse\x12\x0f\n\x07latency\x18\x01 \x01(\x02\x12\x0b\n\x03tps\x18\x02 \x01(\x02\"/\n\x16InitEnvironmentRequest\x12\x15\n\rinstance_name\x18\x01 \x01(\t\"\x19\n\x17InitEnvironmentResponse\"=\n\x15GetActionStateRequest\x12\x15\n\rinstance_name\x18\x01 \x01(\t\x12\r\n\x05knobs\x18\x02 \x03(\t\"\x9c\x01\n\x16GetActionStateResponse\x12\x37\n\x05knobs\x18\x01 \x03(\x0b\x32(.environment.GetActionStateResponse.Knob\x1aI\n\x04Knob\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\x12\x11\n\tmin_value\x18\x03 \x01(\x02\x12\x11\n\tmax_value\x18\x04 \x01(\x02\x32\xc8\x03\n\x0b\x45nvironment\x12J\n\tGetStates\x12\x1d.environment.GetStatesRequest\x1a\x1e.environment.GetStatesResponse\x12S\n\x0c\x41pplyActions\x12 .environment.ApplyActionsRequest\x1a!.environment.ApplyActionsResponse\x12_\n\x10GetRewardMetrics\x12$.environment.GetRewardMetricsRequest\x1a%.environment.GetRewardMetricsResponse\x12\\\n\x0fInitEnvironment\x12#.environment.InitEnvironmentRequest\x1a$.environment.InitEnvironmentResponse\x12Y\n\x0eGetActionState\x12\".environment.GetActionStateRequest\x1a#.environment.GetActionStateResponseB\x08Z\x06pkg/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.environment_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\006pkg/pb'
  _globals['_GETSTATESREQUEST']._serialized_start=38
  _globals['_GETSTATESREQUEST']._serialized_end=79
  _globals['_GETSTATESRESPONSE']._serialized_start=81
  _globals['_GETSTATESRESPONSE']._serialized_end=117
  _globals['_APPLYACTIONSREQUEST']._serialized_start=120
  _globals['_APPLYACTIONSREQUEST']._serialized_end=261
  _globals['_APPLYACTIONSREQUEST_ACTION']._serialized_start=224
  _globals['_APPLYACTIONSREQUEST_ACTION']._serialized_end=261
  _globals['_APPLYACTIONSRESPONSE']._serialized_start=263
  _globals['_APPLYACTIONSRESPONSE']._serialized_end=285
  _globals['_GETREWARDMETRICSREQUEST']._serialized_start=287
  _globals['_GETREWARDMETRICSREQUEST']._serialized_end=335
  _globals['_GETREWARDMETRICSRESPONSE']._serialized_start=337
  _globals['_GETREWARDMETRICSRESPONSE']._serialized_end=393
  _globals['_INITENVIRONMENTREQUEST']._serialized_start=395
  _globals['_INITENVIRONMENTREQUEST']._serialized_end=442
  _globals['_INITENVIRONMENTRESPONSE']._serialized_start=444
  _globals['_INITENVIRONMENTRESPONSE']._serialized_end=469
  _globals['_GETACTIONSTATEREQUEST']._serialized_start=471
  _globals['_GETACTIONSTATEREQUEST']._serialized_end=532
  _globals['_GETACTIONSTATERESPONSE']._serialized_start=535
  _globals['_GETACTIONSTATERESPONSE']._serialized_end=691
  _globals['_GETACTIONSTATERESPONSE_KNOB']._serialized_start=618
  _globals['_GETACTIONSTATERESPONSE_KNOB']._serialized_end=691
  _globals['_ENVIRONMENT']._serialized_start=694
  _globals['_ENVIRONMENT']._serialized_end=1150
# @@protoc_insertion_point(module_scope)
